[WIP] Condor support
casper-ecosystem/casper-manager pull request #7
Opened 2024-12-24 13:19 UTC by KillianH

Left to do : 
- Tests
- Validating the dialog design

2025-02-04 20:29 UTC, davidatwhiletrue commented on packages/snap/src/index.tsx
> +      error: `Unable to convert json into deploy object.`,
@KillianH this error message is not accurate in many cases. Can you add `error.message` to the returned error value?

2025-02-04 20:34 UTC, KillianH commented on packages/snap/src/index.tsx
> +      error: `Unable to convert json into deploy object.`,
Will do that !

2025-02-07 16:34 UTC, davidatwhiletrue requested changes
@KillianH check my comments, please

2025-02-07 17:32 UTC, KillianH commented on packages/snap/src/utils.ts
> +import type { CLValueResult } from 'casper-js-sdk/dist/types/clvalue/Result';
Done

2025-02-07 17:32 UTC, KillianH commented on packages/snap/src/utils.ts
>  } from 'casper-js-sdk';
Cannot, this import is only for types

2025-02-07 17:33 UTC, KillianH commented on packages/snap/src/utils.ts
> +  transferArgs.Recipient = transferDeploy.args.args.get('target')?.toString();
Done

2025-02-07 17:35 UTC, KillianH commented on packages/snap/src/utils.ts
> +      await fetch('https://api.mainnet.casperwallet.io/rates/1/amount', {
Done

2025-02-07 17:36 UTC, KillianH commented on packages/snap/src/utils.ts
> +      bodyHash: Conversions.encodeBase16(transaction.entryPoint.toBytes()),
Done

2025-02-07 17:37 UTC, KillianH commented on packages/snap/src/utils.ts
> +export function parseDeployArg(arg: unknown): string | any[] {
It's because the function is recursive to parse inner args for complex types like maps etc

2025-02-07 17:44 UTC, KillianH commented on packages/snap/src/index.tsx
> +            {Array.isArray(arg[1]) ? (
Nice catch. It was not displaying array args correctly. This is now fixed. Array args are now joined with a comma.

2025-02-07 19:15 UTC, merged